### ISSUE TITLE
ModuleNotFoundError: No module named 'androguard.core.bytecodes' - androguard 4.0.2

### ISSUE THREAD

**Issue by LukeBlueLOx** [google/permhash#4]
For androguard  4.0.2
```
(ANDROID-malicious-app-checker) blox_land@BLOX:~/ANDROID-malicious-app-checker$ python3 permhash_to_csv.py
Traceback (most recent call last):
  File "/home/blox_land/ANDROID-malicious-app-checker/permhash_to_csv.py", line 3, in <module>
    from permhash import functions as permhash
  File "/home/blox_land/ANDROID-malicious-app-checker/ANDROID-malicious-app-checker/lib/python3.11/site-packages/permhash/functions.py", line 18, in <module>
    from permhash.helpers import (
  File "/home/blox_land/ANDROID-malicious-app-checker/ANDROID-malicious-app-checker/lib/python3.11/site-packages/permhash/helpers.py", line 24, in <module>
    from androguard.core.bytecodes import axml
ModuleNotFoundError: No module named 'androguard.core.bytecodes'
(ANDROID-malicious-app-checker) blox_land@BLOX:~/ANDROID-malicious-app-checker$
```
I solved this error by changing the imports in the helpers.py module from "from androguard.core.bytecodes import axml" to "from androguard.core import axml".

Best Wishes

Luke

**Comment by jaredscottwilson** [comment]
Thanks @LukeBlueLOx ! There must have been a change with the androguard code. I confirmed the change works and doesn't impact calculating the permhash.

**Comment by LukeBlueLOx** [comment]
Thanks @jaredscottwilson 👍🙂✌️ - yes, that was a change in androguard code. 
I'm currently using Permhash here:
https://github.com/LukeBlueLOx/ANDROID-malicious-app-checker/blob/main/permhash_to_csv.py
result:
https://github.com/LukeBlueLOx/ANDROID-malicious-app-checker/blob/main/permhash_2024-02-28_17-31-26.csv

https://github.com/LukeBlueLOx/ANDROID-malicious-app-checker/blob/main/find_changes.py
test result:
https://github.com/LukeBlueLOx/ANDROID-malicious-app-checker/blob/main/analysis_of_changes_2024-02-28_12-53-28_vs_2024-02-28_17-31-26.csv

Then I will try to integrate it with VirusTotal.

Best Wishes From Poland
✌️🇵🇱🇵🇱🇵🇱✌️
